# Generated by Django 4.0.8 on 2024-06-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
