# Generated by Django 4.2.13 on 2024-07-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_og'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='og',
            options={'verbose_name': 'Open Graph', 'verbose_name_plural': 'Open Graphs'},
        ),
        migrations.RenameField(
            model_name='og',
            old_name='tipe',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='og',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
