# Generated by Django 4.2.13 on 2024-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_og_options_rename_tipe_og_type_alter_og_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Home Text',
                'verbose_name_plural': 'Home Texts',
            },
        ),
    ]
