# Generated by Django 4.2.13 on 2024-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_hometext_delete_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometext',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='hometext',
            name='title',
        ),
        migrations.AddField(
            model_name='hometext',
            name='en_sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hometext',
            name='en_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hometext',
            name='hy_sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hometext',
            name='hy_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hometext',
            name='ru_sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hometext',
            name='ru_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
