# Generated by Django 4.0.8 on 2024-07-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_delete_hometext'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='og',
            options={'verbose_name': 'HomeText', 'verbose_name_plural': 'HomeTexts'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
    ]
