# Generated by Django 4.0.8 on 2024-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_hometext_alter_og_options_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='og',
            options={'verbose_name': 'Open Graph', 'verbose_name_plural': 'Open Graphs'},
        ),
        migrations.AddField(
            model_name='hometext',
            name='en_sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hometext',
            name='en_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hometext',
            name='hy_sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hometext',
            name='hy_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hometext',
            name='ru_sub_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hometext',
            name='ru_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
