# Generated by Django 4.0.8 on 2024-07-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_alter_og_options_hometext_en_sub_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometext',
            name='lang_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
